# Generated by Django 5.1.1 on 2024-10-09 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0005_rename_prodcutos_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(max_length=500)),
                ('Hora', models.DateTimeField(auto_now=True)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos', to_field='Nombre')),
            ],
        ),
    ]
