# Generated by Django 5.1.1 on 2024-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroventas',
            name='Cantidad',
            field=models.IntegerField(),
        ),
    ]
