# Generated by Django 5.1.1 on 2024-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_prodcutos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcutos',
            name='Nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
