# Generated by Django 5.1.1 on 2024-10-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_alter_prodcutos_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodcutos',
            new_name='Productos',
        ),
    ]
